# Generated by Django 2.0.3 on 2018-03-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_field',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
