# Generated by Django 2.0.3 on 2018-03-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_time_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
