# Generated by Django 2.0.3 on 2018-03-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blogpost_read_time_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='Contact_no',
        ),
    ]
