# Generated by Django 2.0.3 on 2018-03-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20180321_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug_field_post',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_field_category',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
